cir_zs/dip_cir/dip_cir/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from contact import views
# from .views import *
#
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('doc', include('doc.urls')),
    path('new', include('new.urls')),
    path('order_work', views.order_work, name="order_work"),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cir_zs/dip_cir/doc/urls.py
from django.urls import path
from . import views

app_name = 'doc'

urlpatterns = [
    path('', views.docs, name='docs'),
    path('doc/<int:doc_id>', views.r_doc, name='r_doc')
]

cir_zs/dip_cir/new/urls.py
from django.urls import path
from . import views

app_mane = 'new'

urlpatterns = [
    path('', views.news, name='news'),
    ]

cir_zs/dip_cir/contact/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    title = models.CharField(max_length=100, verbose_name="ФИО должность")
    content = models.TextField(blank=True, verbose_name="Контент")
    c_adres = models.TextField(blank=True, verbose_name="Адрес")
    c_mail = models.EmailField()
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Контакты"
        verbose_name_plural = "Контакты"

cir_zs/dip_cir/doc/models.py
from django.db import models

# Create your models here.
class Doc(models.Model):
    title = models.CharField(max_length=100, verbose_name="Название")
    r_doc = models.FileField(upload_to='', blank=True, verbose_name='Файлы')
    # url = models.URLField(blank=True)
    def __str__(self):
            return self.title



# class DocsFiles(models.Model):
#     reg_doc = models.FileField(upload_to='uploads/', blank=True, verbose_name='Файлы')
#     r_doc = models.ForeignKey('Doc', on_delete=models.PROTECT)
#
#     def is_valid(self):
#         pass

    class Meta:
        verbose_name = "Документы"
        verbose_name_plural = "Документы"

cir_zs/dip_cir/new/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class New(models.Model):
    title = models.CharField(max_length=100, verbose_name="Название")
    description = models.CharField(max_length=1500)
    image = models.ImageField(upload_to='new/images/')
    url = models.URLField(blank=True)
    date_new = models.DateField()

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse('post', kwargs={'post_slug': self.slug})

    class Meta:
        verbose_name = "Новость"
        verbose_name_plural = "Новости"
        ordering = ['-date_new']

cir_zs/dip_cir/contact/views.py
from django.shortcuts import render
from .models import Contact


# Create your views here.
def index(request):
    contacts = Contact.objects.all()
    return render(request, 'contact/index.html', {'contacts': contacts})


def order_work(request):
    # order_work = Contact.objects.all()
    return render(request, 'contact/order_work.html', {'order_work':order_work})

cir_zs/dip_cir/doc/views.py
from django.shortcuts import render, get_object_or_404
from .models import Doc
from flask import Flask, request
from django.core.files import File
from django.http import HttpResponseRedirect
import sqlite3
import requests

# Create your views here.




def docs(request):
    docs = Doc.objects.all()
    return render(request, 'doc/docs.html', {'docs': docs})



#
def r_doc(request, doc_id):
    doc = get_object_or_404(Doc, pk=doc_id)
    return render(request, "doc/r_doc.html", {'id': doc})



# def r_doc(request):
#     if request.method == 'POST':
#         doc = Doc(request.POST, request.GET)
#         if doc.is_valid():
#             # file is saved
#             doc.save()
#             return HttpResponseRedirect('/success/url/')
#     else:
#         doc = Doc()
#     return render(request, 'doc/docs.html', {'id': doc})

cir_zs/dip_cir/new/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import New
from django.http import FileResponse, Http404
from django.views.generic import ListView


def news(request):
    new_list = New.objects.all()
    paginator = Paginator(new_list, 3) # Show 25 contacts per page.

    page_number = request.GET.get('page')
    news = paginator.get_page(page_number)
    return render(request, 'new/news.html', {'news': news})


def pdf_view(request):
    try:
        return FileResponse(open('foobar.pdf', 'rb'), content_type='application/pdf')
    except FileNotFoundError:
        raise Http404()

cir_zs/dip_cir/contact/templates/contact/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Центр инновационного развития</title>
    <link rel="icon" type="image/x-icon" href="{% static 'contact/logo.ico' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<header>
    <div class="logo">
       <a href="{% url 'index' %}"><img src="{% static 'contact/cub.png' %}" alt="Центр инновационого развития"
                                         width="4%"></a><h1><i>Центр инновационного развития</i></h1>
    </div>
     <marquee behavior="scroll" bgcolor="silver" direction="left" bgcolor="none" loop="1" scrollamount="10">
        <b>Дипломная работа СУСПИЦИНОЙ МАРИИ</b>
    </marquee>

</header>
<body>
<div class="menu">
    <div class="wrap">
        <ul>
            <li><a href="{% url 'index' %}">Главная</a></li>
            <li><a href="{% url 'news' %}">Новости</a></li>
            <li><a href="{% url 'order_work' %}">Запросы на инновации</a></li>
            <li><a href="{% url 'doc:docs' %}">Нормативные документы</a></li>

        </ul>
    </div>
</div>
<div class="contact">
    <div class="wrap">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>

</html>

cir_zs/dip_cir/contact/templates/contact/index.html
{% extends 'contact/base.html' %}
{% block content %}

{% load static %}
<h1>Центр инновационного развития</h1>

<div class="block">
    {% for contact in contacts %}
    <div class="element">
        <div><h2>{{ contact.title }}</h2>
        {{ contact.content|safe }}<br>
        {{ contact.c_adres|safe }}
        </div>
        <a href="https://innovation.rzd.ru/" target="_blank"><img src="http://qrcoder.ru/code/?https%3A%2F%2Finnovation.rzd.ru%2F&4&0" width="5%"  border="0" title="QR код"></a>
        <div class="mail">
            <b><a href="innovcentre.rzd@mail.ru">{{ contact.c_mail }}</a></b>
        </div>
        <div class="url">
            <b><a href="https://innovation.rzd.ru/" target="_blank">{{ contact.url }}</a></b>
        </div>
    </div>
     {% endfor %}
</div>
<div class="map">
    <a class="dg-widget-link" href="http://2gis.ru/moscow/firm/70000001045473552/center/37.65083312988282,55.772469595530424/zoom/15?utm_medium=widget-source&utm_campaign=firmsonmap&utm_source=bigMap">Посмотреть на карте Москвы</a>
    <div class="dg-widget-link">
        <a href="http://2gis.ru/moscow/center/37.651385,55.771712/zoom/15/routeTab/rsType/bus/to/37.651385,55.771712╎РЖД, центр инновационного развития?utm_medium=widget-source&utm_campaign=firmsonmap&utm_source=route">Найти проезд до РЖД, центр инновационного развития</a>
    </div>
    <script charset="utf-8" src="https://widgets.2gis.com/js/DGWidgetLoader.js"></script>
    <script charset="utf-8">new DGWidgetLoader({"width":640,"height":600,"borderColor":"#a3a3a3","pos":{"lat":55.772469595530424,"lon":37.65083312988282,"zoom":15},"opt":{"city":"moscow"},"org":[{"id":"70000001045473552"}]});</script><noscript style="color:#c00;font-size:16px;font-weight:bold;">Виджет карты использует JavaScript. Включите его в настройках вашего браузера.</noscript>
</div>
{% endblock %}

cir_zs/dip_cir/contact/templates/contact/order_work.html
{% extends 'contact/base.html' %}
{% block content %}

{% load static %}
<div class="element"><section>
<h1>Запросы на инновации</h1>
    <p>С целью внедрения готовых решений, передовых разработок, новой техники и технологий на Западно-Сибирской железной дороге ОАО «РЖД» разработаны «Запросы на инновационные проекты по направлениям», воспользовавшись которым любой поставщик технологий и оборудования может предложить свои наработки для использования в интересах Холдинга.</p>
    <p>Предложения или готовые решения со стороны внешней инновационной среды будут рассмотрены на региональной инновационной площадке с привлечением функциональных заказчиков от железной дороги и разработаны мероприятия по реализации инновационных предложений.</p>
    <p>Обязательным условием рассмотрения является высокая степень проработки предложения с возможностью представить готовое решение и/или прототип для опытной эксплуатации и/или закупки в интересах ОАО «РЖД».</p>
</section>
<section>
<h2>Запросы на инновационные проекты:</h2>
    <p><b><a href="{% static 'contact/ZaprosZS.pdf' %}" target="_blank">Перечень запросов на инновации</a></b></p>
</section>
<section>
<h2>Открытые запросы</h2>
    <p>Начиная с 2018 года в ОАО «РЖД» успешно реализуется инструмент открытого запроса – процедура поиска инновационных предложений для решения актуальных для ОАО «РЖД» задач (запросов на инновации) с возможностью их опытной эксплуатации (испытаний) и / или закупки. Процедура открытого запроса позволяет в сжатые сроки задействовать промышленный и инновационный потенциал российских и зарубежных компаний в интересах Холдинга. Преимуществами данного инструмента является возможность в короткие сроки довести до неограниченного круга лиц конкретные потребности ОАО «РЖД» в инновационных решениях, а высокотехнологичным организациям внешнего по отношению к ОАО «РЖД» контура заявить и в дальнейшем апробировать лучшие инновационные решения на сети ОАО «РЖД» в краткосрочной перспективе.</p>
<p>В рамках направления Центром инновационного развития – филиалом ОАО «РЖД» впервые сформирован расширенный перечень востребованных для функциональных подразделений ОАО «РЖД» тематик открытых запросов, составляющий более сотни наименований. К приоритетным направлениями следует отнести: повышение энергетической эффективности основной деятельности, безопасность и надежность производственных процессов, развитие, мониторинг и обслуживание инфраструктуры и подвижного состава на основе внедрения инновационных высокопроизводительных технологий, динамические системы управления перевозочным процессом с использованием искусственного интеллекта, инновационные телекоммуникационные решения, научно-техническое обеспечение природоохранной деятельности.</p>
    <p>Прием заявок осуществляется через раздел «Запросы» информационно-функционального ресурса <b><a href="https://eoi.rzd.ru/front/запросы" target="_blank">«Единое окно инноваций ОАО «РЖД».</a></b>
    <p><b><i>Установленные на правила представления и оформления инновационных предложений зависят от предлагаемого вами инновационного объекта:</i></b></p>
    <ul>
    <li>Готовый инновационный товар (услуга), предлагаемый для закупки</li>
    <li>Инновационные предложения (проекты), которые будут использованы в ОАО «РЖД».</li>
    </ul>

</section>
</div>
{% endblock %}

cir_zs/dip_cir/doc/templates/doc/docs.html
{% extends 'contact/base.html' %}
{% block content %}
<h1>Нормативные документы, буклеты, подборки</h1>
<h2 class = 'count'>Всего документов: {{  docs.count }}</h2>
{% for doc in docs %}
<div class="element">
    <p class="top"><i><a href="{{ doc.r_doc.url }}" target="_blank">{{ doc.title }} </a></i></p>
</div>
{% endfor %}

{% endblock %}

cir_zs/dip_cir/doc/templates/doc/r_doc.html
{% extends 'contact/base.html' %}
{% block content %}
<div>
 {{ id }}
 {{ r_doc }}
</div>


{% endblock %}

cir_zs/dip_cir/new/templates/new/news.html
{% extends 'contact/base.html' %}
{% block content %}
<h1>Новости</h1>
<!--<h2 class = 'count'>Новостей: {{  news.count }}</h2>-->
{% for new in news %}
<div class="element">
    <div class="border">
    <h2 class="top">{{ new.title }}</h2>
    <img src="{{ new.image.url }}" alt="" width="20%">
    <div class="new_text">
        <p>{{ new.description|safe }}</p>
        <h5>{{ new.date_new }}</h5>
    </div>
    </div>
</div>
{% endfor %}

<div>
     <span class="step-links">
        {% if news.has_previous %}
            <a href="?page=1">&laquo;</a>
            <a href="?page={{ news.previous_page_number }}">Предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ news.number }} из {{ news.paginator.num_pages }}_
        </span>

        {% if news.has_next %}
            <a href="?page={{ news.next_page_number }}">Следующая</a>
            <a href="?page={{ news.paginator.num_pages }}"> &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}